[build-system]
requires = [
    "setuptools"
]

[tool.pytest.ini_options]
markers = [
    "eda: this test requires EDA tools installed to run. By default these tests will be run nightly, not on push.",
    "quick: always run this test on push, even if it requires EDA tools.",
    "remote_test: marker used to pass 'port' variables into remote flow fixtures.",
    "nostrict: don't automatically set [option, strict] parameter for Chip objects in this test.",
]
testpaths = "tests"
timeout = "120"
