[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cython",
    "scikit-build>=0.12",
    "cmake"
]

build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
markers = [
    "eda: marks tests that require EDA tools installed to run",
]
