exclude = [
    'third_party',
    'siliconcompiler/tools/yosys/syn_strategies.tcl'
]

# codebase uses mix of indent styles - can enforce once one is chosen
ignore = ['indent']

[style]
allow-aligned-sets = true
line-length = 100
