name: Feature Request
description: "Submit a feature request for SiliconCompiler"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: >
        If you have a general question, please ask it in the [Discussions](https://github.com/siliconcompiler/siliconcompiler/discussions) area.

        If you have a bug report, please fill out the appropriate issue form, this form is for feature requests.

  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: "A clear and detailed description of the feature."
    validations:
      required: true
