name: sc_env
channels:
  - LiteX-Hub
  - conda-forge
dependencies:
  - pip
  - pip:
    - siliconcompiler

  - surelog>=1.51
  - openroad>=2.0-11974
  - magic>=8.3.196
  - netgen
  - yosys>=0.33+21
  - klayout>=0.28.0
  - fmt # Requirement for OpenROAD
  - ruby==2.5.1 # Requirement for klayout
