on: [workflow_dispatch, push]

name: 'Documentation'

jobs:
  docs_test_job:
    timeout-minutes: 10
    runs-on: self-hosted
    name: 'Test documentation build'
    steps:
      - uses: actions/checkout@v2
      - run: |
          python3 -m venv create $GITHUB_WORKSPACE/clean_env --clear
          source $GITHUB_WORKSPACE/clean_env/bin/activate
          echo $VIRTUAL_ENV
          pip3 install -r $GITHUB_WORKSPACE/requirements.txt -e $GITHUB_WORKSPACE/.
          cd docs
          make html
