on: [workflow_dispatch, pull_request, pull_request_review, push]

jobs:
  gcd_test_job:
    runs-on: self-hosted
    name: 'ASIC test builds'
    steps:
      - timeout-minutes: 10
      - uses: actions/checkout@v2
      - run: |
          python3 -m venv create $GITHUB_WORKSPACE/clean_env --clear
          source $GITHUB_WORKSPACE/clean_env/bin/activate
          echo $VIRTUAL_ENV
          pip3 install -r $GITHUB_WORKSPACE/requirements.txt -e $GITHUB_WORKSPACE/.
          pytest $GITHUB_WORKSPACE/tests/asic/
  fpga_test_job:
    runs-on: self-hosted
    name: 'FPGA test builds'
    steps:
      - timeout-minutes: 10
      - uses: actions/checkout@v2
      - run: |
          python3 -m venv create $GITHUB_WORKSPACE/clean_env --clear
          source $GITHUB_WORKSPACE/clean_env/bin/activate
          echo $VIRTUAL_ENV
          pip3 install -r $GITHUB_WORKSPACE/requirements.txt -e $GITHUB_WORKSPACE/.
          PATH="$HOME/OpenFPGA/openfpga:$PATH"
          pytest $GITHUB_WORKSPACE/tests/fpga/
  python_test_job:
    runs-on: self-hosted
    name: 'Python unit tests'
    steps:
      - timeout-minutes: 5
      - uses: actions/checkout@v2
      - run: |
          python3 -m venv create $GITHUB_WORKSPACE/clean_env --clear
          source $GITHUB_WORKSPACE/clean_env/bin/activate
          pip3 install -r $GITHUB_WORKSPACE/requirements.txt -e $GITHUB_WORKSPACE/.
          python3 -m unittest
