on: [push, pull_request, pull_request_review]

jobs:
  gcd_test_job:
    runs-on: self-hosted
    name: 'GCD test build'
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install -r $GITHUB_WORKSPACE/requirements.txt
      - run: pip3 install -e $GITHUB_WORKSPACE/.
      - run: $GITHUB_WORKSPACE/examples/gcd/test.sh
  fpga_test_job:
    runs-on: self-hosted
    name: 'FPGA test builds'
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install -r $GITHUB_WORKSPACE/requirements.txt
      - run: pip3 install -e $GITHUB_WORKSPACE/.
      - run: |
          PATH="$HOME/OpenFPGA/openfpga:$PATH"
          $GITHUB_WORKSPACE/examples/blinky/test.sh
          $GITHUB_WORKSPACE/examples/and2_openfpga/test.sh
