on: [workflow_dispatch, pull_request, pull_request_review]

jobs:
  gcd_test_job:
    runs-on: self-hosted
    name: 'GCD test build'
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install -r $GITHUB_WORKSPACE/requirements.txt
      - run: pip3 install -e $GITHUB_WORKSPACE/.
      - run: $GITHUB_WORKSPACE/examples/gcd/test.sh
  gcd_loopback_test:
    runs-on: self-hosted
    name: 'GCD "local server" test build'
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install -r $GITHUB_WORKSPACE/requirements.txt
      - run: pip3 install -e $GITHUB_WORKSPACE/.
      - run: $GITHUB_WORKSPACE/examples/gcd/test_server.sh
  gcd_permutations_test:
    runs-on: self-hosted
    name: 'GCD test build with two permutations'
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install -r $GITHUB_WORKSPACE/requirements.txt
      - run: pip3 install -e $GITHUB_WORKSPACE/.
      - run: $GITHUB_WORKSPACE/examples/gcd/test_permutations.sh
  gcd_loopback_permutations_test:
    runs-on: self-hosted
    name: 'GCD "local server" test build with two permutations'
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install -r $GITHUB_WORKSPACE/requirements.txt
      - run: pip3 install -e $GITHUB_WORKSPACE/.
      - run: $GITHUB_WORKSPACE/examples/gcd/test_server_permutations.sh
  fpga_test_job:
    runs-on: self-hosted
    name: 'FPGA test builds'
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install -r $GITHUB_WORKSPACE/requirements.txt
      - run: pip3 install -e $GITHUB_WORKSPACE/.
      - run: |
          PATH="$HOME/OpenFPGA/openfpga:$PATH"
          $GITHUB_WORKSPACE/examples/blinky/test.sh
          $GITHUB_WORKSPACE/examples/and2_openfpga/test.sh
  python_test_job:
    runs-on: self-hosted
    name: 'Python unit tests'
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install -r $GITHUB_WORKSPACE/requirements.txt
      - run: pip3 install -e $GITHUB_WORKSPACE/.
      - run: python3 -m unittest
