name: Lint
on:
  # Runs on all pushes to branches
  push:
  # Runs on all PRs
  pull_request:
  # Manual Dispatch
  workflow_dispatch:

jobs:
  lint_python:
    name: Lint Python Code
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Lint with Flake8
        run: |
          python -m pip install flake8
          flake8 --statistics .

  lint_verilog:
    name: Lint Verilog Code
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Verible
        run: |
          ./setup/install-verible.sh
          echo /opt/verible/bin >> $GITHUB_PATH

      - name: Check format
        id: check-format
        run: |
          ./.github/workflows/bin/format_verilog.sh > files.txt
          cat files.txt
          git diff --exit-code

      - name: Check lint
        if: success() || steps.check-format.conclusion == 'failure'
        run: |
          verible-verilog-lint --rules_config .github/workflows/config/verible.rules `cat files.txt`
