on: [workflow_dispatch]

jobs:
  gcd_test_job:
    runs-on: self-hosted
    name: 'GCD test build'
    steps:
      - uses: WRansohoff/siliconcompiler@sc_actions_test
      - run: ./examples/gcd/test.sh
