on: [workflow_dispatch, push]

name: 'Quick CI Tests'

jobs:
  self_hosted_tests:
    timeout-minutes: 15
    runs-on: self-hosted
    name: 'Self-hosted tests'
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive third_party/tools/openroad
      - run: git submodule update --init --recursive third_party/designs/oh
      - run: |
          python3 -m venv create $GITHUB_WORKSPACE/clean_env --clear
          source $GITHUB_WORKSPACE/clean_env/bin/activate
          echo $VIRTUAL_ENV
          echo $TEST_PATHS
          pip3 install -r $GITHUB_WORKSPACE/requirements.txt -e $GITHUB_WORKSPACE/.
          PATH="$HOME/OpenFPGA/openfpga:$PATH"
          pytest -n 4 $TEST_PATHS
        env:
          TEST_PATHS: >
            ${{ github.workspace }}/tests/quick_tests/asic
            ${{ github.workspace }}/tests/quick_tests/fpga
            ${{ github.workspace }}/tests/tools

  python_test_job:
    timeout-minutes: 5
    runs-on: self-hosted
    name: 'Python unit tests'
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive third_party/tools/openroad
      - run: |
          python3 -m venv create $GITHUB_WORKSPACE/clean_env --clear
          source $GITHUB_WORKSPACE/clean_env/bin/activate
          pip3 install -r $GITHUB_WORKSPACE/requirements.txt -e $GITHUB_WORKSPACE/.
          pytest $GITHUB_WORKSPACE/tests/quick_tests/python/ $GITHUB_WORKSPACE/tests/api_tests/
