on: [workflow_dispatch, push]

name: 'Quick CI Tests'

jobs:
  self_hosted_tests:
    timeout-minutes: 15
    runs-on: self-hosted
    name: 'Tool-based tests'
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive third_party/tools/openroad
      - run: git submodule update --init --recursive third_party/designs/oh
      - run: git submodule update --init --recursive third_party/designs/picorv32
      - run: |
          python3 -m venv create $GITHUB_WORKSPACE/clean_env --clear
          source $GITHUB_WORKSPACE/clean_env/bin/activate
          echo $VIRTUAL_ENV
          echo $TEST_PATHS
          pip3 install -r $GITHUB_WORKSPACE/requirements.txt $GITHUB_WORKSPACE/.
          PATH="$HOME/OpenFPGA/openfpga:$PATH"
          pytest -n 4 --import-mode=append -m "eda and quick"

  python_test_job:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    name: 'Pure Python tests'
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2

      - run: git submodule update --init --recursive third_party/tools/openroad

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install graphviz

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - run: |
          pip install $GITHUB_WORKSPACE/.
          pip install pytest pyvirtualdisplay
          pytest --import-mode=append -m "not eda"
