name: Wheels

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Clone OpenROAD submodule
      run: git submodule update --init --recursive third_party/tools/openroad

    - uses: pypa/cibuildwheel@v2.1.1
      env:
        CIBW_BEFORE_BUILD_LINUX: yum install -y zlib-devel
        CIBW_BEFORE_BUILD_WINDOWS: choco install winflexbison3 && vcpkg install zlib zlib:x64-windows
        CIBW_ENVIRONMENT_WINDOWS: SC_CMAKEARGS="-DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake."
        CIBW_SKIP: pp*, *win32, *i686

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        path: wheelhouse/*.whl
