name: Wheels

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Clone tool submodules
      run: git submodule update --init --recursive third_party/tools

    - name: Get Surelog version
      id: get-surelog
      run: |
        echo "::set-output name=version::$(cd third_party/tools/surelog && git rev-parse HEAD)"

    - uses: actions/cache@v2
      id: surelog-cache
      if: matrix.os != 'ubuntu-latest'
      with:
        path: |
          siliconcompiler/tools/surelog/bin/surelog*
          siliconcompiler/tools/surelog/lib/surelog/sv/builtin.sv
        key: ${{ matrix.os }}-${{ steps.get-surelog.outputs.version }}

    - name: Setup env (Windows)
      if: matrix.os == 'windows-latest'
      run: choco install -y graphviz

    - name: Setup env (macOS)
      if: matrix.os == 'macos-latest'
      run: brew install graphviz

    - name: Build Surelog (Windows)
      if: matrix.os == 'windows-latest' && steps.surelog-cache.outputs.cache-hit != 'true'
      run: .github/workflows/bin/setup_wheel_env_win.bat

    - name: Build Surelog (macOS)
      if: matrix.os == 'macos-latest' && steps.surelog-cache.outputs.cache-hit != 'true'
      run: .github/workflows/bin/setup_wheel_env_macos.sh

    - uses: pypa/cibuildwheel@v2.1.1
      env:
        CIBW_BEFORE_ALL_LINUX: >
          export PREFIX={package}/siliconcompiler/tools/surelog &&
          {package}/.github/workflows/bin/setup_wheel_env_linux.sh
        CIBW_ENVIRONMENT_WINDOWS: SC_CMAKEARGS="-DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake."
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
        CIBW_SKIP: "pp* *win32 *i686"
        MACOSX_DEPLOYMENT_TARGET: "10.15"
        CIBW_TEST_EXTRAS: test
        CIBW_TEST_COMMAND: >
          pytest --import-mode=append {package}/tests/ -m "not eda" &&
          pytest --import-mode=append {package}/tests/tools/test_surelog.py
    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        path: wheelhouse/*.whl
